defmodule RapierLab.MobApp do
  @moduledoc """
  On-device entry point (the `mix mob.adopt` thin-client shape, hand-
  written because the guarded adopt tasks refuse non-Phoenix projects
  by policy — same shape as `Crosscourt.MobApp`).

  `src/rapier_lab.erl` calls `start/0` (generated by `use Mob.App`),
  which boots the Mob runtime and then `on_start/0`.
  """

  use Mob.App

  @impl Mob.App
  def navigation(_platform) do
    stack(:main, root: RapierLab.Screens.MainScreen)
  end

  @impl Mob.App
  def on_start do
    Application.put_env(:mob_scene3d, :asset_root, {:rapier_lab, "priv/assets"})

    Mob.DNS.configure_pure_beam()
    Mob.Screen.start_root(RapierLab.Screens.MainScreen)

    Mob.Dist.ensure_started(
      node: :"rapier_lab@127.0.0.1",
      cookie: :mob_secret
    )
  end
end
